sudo: false
language: node_js
node_js:
    - "8"
    - "10"
    - "12"
services:
    - mongodb
cache:
    directories:
        - node_modules
before_script:
    - npm install -g expo-cli
script:
    - yarn build
    - yarn test