export const LOAD_COMMENTS_START: string = "LOAD_COMMENTS_START";
export const LOAD_COMMENTS_SUCCESS: string = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_FAILED: string = "LOAD_COMMENTS_FAILED";
export const ADD_COMMENT_START: string = "ADD_COMMENT_START";
export const ADD_COMMENT_SUCCESS: string = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILED: string = "ADD_COMMENT_FAILED";
export const UPDATE_COMMENT_START: string = "UPDATE_COMMENT_START";
export const UPDATE_COMMENT_SUCCESS: string = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAILED: string = "UPDATE_COMMENT_FAILED";
export const RATE_COMMENT_SUCCESS: string = "RATE_COMMENT_SUCCESS";
export const RATE_COMMENT_FAILED: string = "RATE_COMMENT_FAILED";
// TODO